# Generated by Django 4.1.3 on 2022-11-20 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geziler', '0002_remove_content_image_remove_setting_aboutus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='category',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='isHome',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=50, null=True, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(max_length=50, null=True, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geziler.content'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.BooleanField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geziler.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='Şifre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=50, null=True, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(max_length=50, null=True, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='Soyisim'),
        ),
    ]
