# Generated by Django 4.1.3 on 2022-11-20 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziler', '0003_remove_category_parent_id_category_isactive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='keywords',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='keywords',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Açıklama'),
        ),
    ]
