# Generated by Django 4.1.3 on 2022-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziler', '0004_rename_keywords_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.TextField(max_length=50, null=True, verbose_name='Slug Adı'),
        ),
    ]
