# Generated by Django 4.1.3 on 2022-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziler', '0005_alter_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='titleforhead',
            field=models.CharField(max_length=50, null=True, verbose_name='Kafa Başlığı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='Slug Adı'),
        ),
    ]
