# Generated by Django 4.1.3 on 2022-11-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziler', '0007_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='geziler', verbose_name='Resim'),
        ),
    ]
