# Generated by Django 4.1.3 on 2022-11-21 07:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziler', '0008_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=50, null=True, verbose_name='Resim'),
        ),
    ]
