# Generated by Django 4.1.3 on 2022-11-21 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziler', '0009_alter_category_description_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imagecover',
            field=models.CharField(max_length=50, null=True, verbose_name='Kapak Fotografi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Açıklama'),
        ),
    ]
