# Generated by Django 4.1.3 on 2022-11-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geziler', '0013_remove_comment_comment_remove_comment_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
