# Generated by Django 4.1.3 on 2022-11-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geziler', '0017_rename_category_comment_gezi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='gezi',
            new_name='category',
        ),
    ]
