# Generated by Django 4.1.3 on 2022-12-08 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geziler', '0019_rename_category_comment_gezi_remove_category_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='geziler')),
                ('gezi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geziler.category')),
            ],
        ),
    ]
